### PR TITLE
Simplify plugin using modify-babel-preset

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by gajus** [comment]
I don't feel comfortable merging this given that:
- `babel-preset-es2015` is unlikely to change.
- The current implementation is working fine.
- The workings of [`modify-babel-preset`](https://github.com/developit/modify-babel-preset/blob/24bad7610c145baf13b867ecccbedd0dc679d705/index.js) function are not straightforward.

Will leave this open until/if there is an issue that `modify-babel-preset` can solve.

**Comment by SimenB** [comment]
Sounds perfectly reasonable, just adding my two cents

> babel-preset-es2015 is unlikely to change.
> The current implementation is working fine.

Fair enough, doesn't mean you have to duplicate what it contains, though, instead of just modifying it.

> The workings of modify-babel-preset function are not straightforward.

Also quite fair, but I do disagree on it. It's very simple regex-matching, and array mutations, and soundly tested.

On the other hand, I do agree that the current version does work, so if you're not comfortable with the dep, I have no problem with you not merging

**Comment by gajus** [comment]
> On the other hand, I do agree that the current version does work, so if you're not comfortable with the dep, I have no problem with you not merging

Sorry for the lack of contribution guidelines.

**Comment by taion** [comment]
modify-babel-preset is pretty commonly used for a number of presets, though, e.g. babel-preset-es2015-loose.

It's a little opaque internally, sure, but it makes it much easier to tell what this specific preset is doing.

**Pull request closed without merging**
